version: '3.7'
services:
  rancher:
    image: rancher/rancher:latest
    restart: always
    ports:
    - "843:80/tcp"
    - "4493:443/tcp"
    volumes:
    - "./rancher-data:/var/lib/rancher"
    privileged: true
    networks:
    - app-network

#Docker Networks
# docker network create app-network
networks:
  app-network:
    driver: bridge
    external: true
#Volumes
volumes:
  dbdata:
    driver: local
